import type { User } from '@/types/auth'

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Amar Daxini',
    email: 'amar@comprinttech.com',
    avatar: '',
    role: 'SUPERADMIN',
    permissions: [],
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya@comprinttech.com',
    avatar: '',
    role: 'ADMIN',
    permissions: [],
  },
  {
    id: '3',
    name: 'Rahul Mehta',
    email: 'rahul@comprinttech.com',
    avatar: '',
    role: 'PRODUCT_MANAGER',
    permissions: [],
    assignedCategories: ['servers', 'storage'],
  },
  {
    id: '4',
    name: 'Sneha Patel',
    email: 'sneha@comprinttech.com',
    avatar: '',
    role: 'SALES_MANAGER',
    permissions: [],
    assignedCategories: ['Servers', 'Storage', 'Networking', 'Laptops', 'Desktops'],
  },
  {
    id: '5',
    name: 'Vikram Singh',
    email: 'vikram@comprinttech.com',
    avatar: '',
    role: 'WAREHOUSE_MANAGER',
    permissions: [],
  },
  {
    id: '6',
    name: 'Anita Desai',
    email: 'anita@comprinttech.com',
    avatar: '',
    role: 'TECHNICAL_TEAM',
    permissions: [],
  },
  {
    id: '7',
    name: 'Kiran Joshi',
    email: 'kiran@comprinttech.com',
    avatar: '',
    role: 'FINANCE_MANAGER',
    permissions: [],
  },
  {
    id: '8',
    name: 'Deepak Kumar',
    email: 'deepak@comprinttech.com',
    avatar: '',
    role: 'VIEWER',
    permissions: [],
  },
  {
    id: '9',
    name: 'Meera Kapoor',
    email: 'meera@comprinttech.com',
    avatar: '',
    role: 'CRM_CHANNEL_MANAGER',
    permissions: [],
    assignedCategories: ['Servers', 'Storage', 'Networking'],
  },
  {
    id: '10',
    name: 'Arjun Nair',
    email: 'arjun@comprinttech.com',
    avatar: '',
    role: 'CRM_BDE_CHANNEL',
    permissions: [],
    assignedCategories: ['Servers'],
  },
  {
    id: '11',
    name: 'Divya Reddy',
    email: 'divya@comprinttech.com',
    avatar: '',
    role: 'CRM_INSIDE_SALES_REP',
    permissions: [],
    assignedCategories: ['Laptops', 'Desktops'],
  },
  {
    id: '12',
    name: 'Sanjay Patil',
    email: 'sanjay@comprinttech.com',
    avatar: '',
    role: 'CRM_SUPPORT_AGENT',
    permissions: [],
    assignedCategories: ['Servers', 'Networking'],
  },
]
