import type { User } from '@/types/auth'

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Amar Daxini',
    email: 'amar@comprinttech.com',
    avatar: '',
    role: 'SUPERADMIN',
    permissions: [],
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya@comprinttech.com',
    avatar: '',
    role: 'ADMIN',
    permissions: [],
  },
  {
    id: '3',
    name: 'Rahul Mehta',
    email: 'rahul@comprinttech.com',
    avatar: '',
    role: 'PRODUCT_MANAGER',
    permissions: [],
    assignedCategories: ['servers', 'storage'],
  },
  {
    id: '4',
    name: 'Sneha Patel',
    email: 'sneha@comprinttech.com',
    avatar: '',
    role: 'SALES_MANAGER',
    permissions: [],
  },
  {
    id: '5',
    name: 'Vikram Singh',
    email: 'vikram@comprinttech.com',
    avatar: '',
    role: 'WAREHOUSE_MANAGER',
    permissions: [],
  },
  {
    id: '6',
    name: 'Anita Desai',
    email: 'anita@comprinttech.com',
    avatar: '',
    role: 'TECHNICAL_TEAM',
    permissions: [],
  },
  {
    id: '7',
    name: 'Kiran Joshi',
    email: 'kiran@comprinttech.com',
    avatar: '',
    role: 'FINANCE_MANAGER',
    permissions: [],
  },
  {
    id: '8',
    name: 'Deepak Kumar',
    email: 'deepak@comprinttech.com',
    avatar: '',
    role: 'VIEWER',
    permissions: [],
  },
]
