import {
  LayoutDashboard,
  Users,
  Handshake,
  Building2,
  Contact,
  ShoppingCart,
  FileText,
  Receipt,
  Warehouse,
  PackageSearch,
  ClipboardCheck,
  Wrench,
  Paintbrush,
  CheckCircle2,
  Truck,
  Package,
  Boxes,
  FolderTree,
  Tags,
  BarChart3,
  FilePlus,
  FileCheck,
  Store,
  ClipboardList,
  ArrowLeftRight,
  Landmark,
  CreditCard,
  Globe,
  ShoppingBag,
  ListOrdered,
  UserPlus,
  Shield,
  Settings,
  UserCircle,
  Scale,
  CalendarClock,
  FileBox,
  RotateCcw,
  MapPin,
} from 'lucide-react'
import type { NavGroup } from '@/types/navigation'

export const SIDEBAR_NAV: NavGroup[] = [
  {
    label: 'CRM',
    module: 'crm',
    icon: Users,
    items: [
      { label: 'Dashboard', href: '/crm', icon: LayoutDashboard, module: 'crm' },
      { label: 'Leads', href: '/crm/leads', icon: Users, module: 'crm' },
      { label: 'Deals', href: '/crm/deals', icon: Handshake, module: 'crm' },
      { label: 'Accounts', href: '/crm/accounts', icon: Building2, module: 'crm' },
      { label: 'Contacts', href: '/crm/contacts', icon: Contact, module: 'crm' },
      { label: 'Sales Orders', href: '/crm/sales-orders', icon: ShoppingCart, module: 'crm' },
      { label: 'Quotes', href: '/crm/quotes', icon: FileText, module: 'crm' },
      { label: 'Purchase Requests', href: '/crm/purchase-requests', icon: FilePlus, module: 'crm' },
      { label: 'Material Inquiries', href: '/crm/material-inquiries', icon: PackageSearch, module: 'crm' },
    ],
  },
  {
    label: 'Warehouse',
    module: 'wms',
    icon: Warehouse,
    items: [
      { label: 'Dashboard', href: '/wms', icon: LayoutDashboard, module: 'wms' },
      { label: 'Inward / GRN', href: '/wms/inward', icon: PackageSearch, module: 'wms' },
      { label: 'Inspection', href: '/wms/inspection', icon: ClipboardCheck, module: 'wms' },
      { label: 'Repair', href: '/wms/repair', icon: Wrench, module: 'wms' },
      { label: 'Paint', href: '/wms/paint', icon: Paintbrush, module: 'wms' },
      { label: 'QC', href: '/wms/qc', icon: CheckCircle2, module: 'wms' },
      { label: 'Outward', href: '/wms/outward', icon: Truck, module: 'wms' },
      { label: 'Dispatch', href: '/wms/dispatch', icon: Package, module: 'wms' },
      { label: 'Checklists', href: '/wms/checklists', icon: ClipboardList, module: 'wms' },
      { label: 'Locations', href: '/wms/locations', icon: MapPin, module: 'wms' },
    ],
  },
  {
    label: 'Inventory',
    module: 'ims',
    icon: Boxes,
    items: [
      { label: 'Dashboard', href: '/ims', icon: LayoutDashboard, module: 'ims' },
      { label: 'Inventory', href: '/ims/inventory', icon: Boxes, module: 'ims' },
      { label: 'Categories', href: '/ims/categories', icon: FolderTree, module: 'ims' },
      { label: 'Stock Items', href: '/ims/stock-items', icon: Tags, module: 'ims' },
      { label: 'Reports', href: '/ims/reports', icon: BarChart3, module: 'ims' },
    ],
  },
  {
    label: 'Procurement',
    module: 'procurement',
    icon: ClipboardList,
    items: [
      { label: 'Dashboard', href: '/procurement', icon: LayoutDashboard, module: 'procurement' },
      { label: 'Purchase Requests', href: '/procurement/pr', icon: FilePlus, module: 'procurement' },
      { label: 'Approvals', href: '/procurement/approvals', icon: FileCheck, module: 'procurement' },
    ],
  },
  {
    label: 'Purchase Orders',
    module: 'purchase-orders',
    icon: FileText,
    items: [
      { label: 'Dashboard', href: '/purchase-orders', icon: LayoutDashboard, module: 'purchase-orders' },
      { label: 'PO List', href: '/purchase-orders/list', icon: FileText, module: 'purchase-orders' },
      { label: 'GRN Matching', href: '/purchase-orders/grn-matching', icon: ArrowLeftRight, module: 'purchase-orders' },
    ],
  },
  {
    label: 'Invoices',
    module: 'invoices',
    icon: Receipt,
    items: [
      { label: 'Dashboard', href: '/invoices', icon: LayoutDashboard, module: 'invoices' },
      { label: 'Sales Invoices', href: '/invoices/sales', icon: Receipt, module: 'invoices' },
      { label: 'Purchase Invoices', href: '/invoices/purchase', icon: FileText, module: 'invoices' },
      { label: 'Credit Notes', href: '/invoices/credit-notes', icon: FileBox, module: 'invoices' },
    ],
  },
  {
    label: 'Accounting',
    module: 'accounting',
    icon: Landmark,
    items: [
      { label: 'Dashboard', href: '/accounting', icon: LayoutDashboard, module: 'accounting' },
      { label: 'Ledger', href: '/accounting/ledger', icon: Landmark, module: 'accounting' },
      { label: 'Payments', href: '/accounting/payments', icon: CreditCard, module: 'accounting' },
      { label: 'Reports', href: '/accounting/reports', icon: BarChart3, module: 'accounting' },
    ],
  },
  {
    label: 'Reconciliation',
    module: 'reconciliation',
    icon: Scale,
    items: [
      { label: 'Bank', href: '/reconciliation/bank', icon: Landmark, module: 'reconciliation' },
      { label: 'Vendor', href: '/reconciliation/vendor', icon: Store, module: 'reconciliation' },
      { label: 'Inventory', href: '/reconciliation/inventory', icon: Boxes, module: 'reconciliation' },
      { label: 'Inter-module', href: '/reconciliation/inter-module', icon: ArrowLeftRight, module: 'reconciliation' },
    ],
  },
  {
    label: 'E-commerce',
    module: 'ecommerce',
    icon: Globe,
    items: [
      { label: 'Dashboard', href: '/ecommerce', icon: LayoutDashboard, module: 'ecommerce' },
      { label: 'Catalog', href: '/ecommerce/catalog', icon: ShoppingBag, module: 'ecommerce' },
      { label: 'Products', href: '/ecommerce/products', icon: Tags, module: 'ecommerce' },
      { label: 'Orders', href: '/ecommerce/orders', icon: ListOrdered, module: 'ecommerce' },
    ],
  },
  {
    label: 'Vendors',
    module: 'vendors',
    icon: Store,
    items: [
      { label: 'Vendor List', href: '/vendors', icon: Store, module: 'vendors' },
      { label: 'Approvals', href: '/vendors/approvals', icon: FileCheck, module: 'vendors' },
    ],
  },
  {
    label: 'Customers',
    module: 'customers',
    icon: UserPlus,
    items: [
      { label: 'Customer List', href: '/customers', icon: UserPlus, module: 'customers' },
      { label: 'Approvals', href: '/customers/approvals', icon: FileCheck, module: 'customers' },
    ],
  },
  {
    label: 'Rentals',
    module: 'rentals',
    icon: CalendarClock,
    items: [
      { label: 'Dashboard', href: '/rentals', icon: LayoutDashboard, module: 'rentals' },
      { label: 'Contracts', href: '/rentals/contracts', icon: FileText, module: 'rentals' },
      { label: 'Device Tracking', href: '/rentals/tracking', icon: MapPin, module: 'rentals' },
      { label: 'Returns', href: '/rentals/returns', icon: RotateCcw, module: 'rentals' },
    ],
  },
  {
    label: 'Reports',
    module: 'reports',
    icon: BarChart3,
    items: [
      { label: 'Report Builder', href: '/reports', icon: BarChart3, module: 'reports' },
    ],
  },
  {
    label: 'Settings',
    module: 'settings',
    icon: Settings,
    items: [
      { label: 'Profile', href: '/settings/profile', icon: UserCircle, module: 'settings' },
      { label: 'User Management', href: '/settings/users', icon: Users, module: 'settings', requiredRole: 'ADMIN' },
      { label: 'Roles & Permissions', href: '/settings/roles', icon: Shield, module: 'settings', requiredRole: 'ADMIN' },
      { label: 'App Settings', href: '/settings/app', icon: Settings, module: 'settings' },
    ],
  },
]
