import {
  LayoutDashboard,
  Users,
  Handshake,
  Building2,
  Contact,
  ShoppingCart,
  FileText,
  Receipt,
  Warehouse,
  PackageSearch,
  ClipboardCheck,
  Wrench,
  Paintbrush,
  CheckCircle2,
  Truck,
  Package,
  Boxes,
  FolderTree,
  Tags,
  BarChart3,
  FilePlus,
  Store,
  ClipboardList,
  ArrowLeftRight,
  Shield,
  Settings,
  UserCircle,
  CalendarClock,
  FileBox,
  RotateCcw,
  MapPin,
  Monitor,
  ShieldCheck,
  ListTodo,
  Video,
  Calendar,
  Factory,
  UserCog,
  DollarSign,
  History,
  XCircle,
  Cpu,
  LocateFixed,
  FileCheck,
} from 'lucide-react'
import type { NavGroup } from '@/types/navigation'

export const SIDEBAR_NAV: NavGroup[] = [
  {
    label: 'CRM',
    module: 'crm',
    icon: Users,
    items: [
      { label: 'Dashboard', href: '/crm', icon: LayoutDashboard, module: 'crm' },
      { label: 'Leads', href: '/crm/leads', icon: Users, module: 'crm', accessLevel: 'pre-sales' },
      { label: 'Rejected Leads', href: '/crm/rejected-leads', icon: XCircle, module: 'crm', accessLevel: 'pre-sales' },
      { label: 'Deals', href: '/crm/deals', icon: Handshake, module: 'crm', accessLevel: 'pre-sales' },
      { label: 'Accounts', href: '/crm/accounts', icon: Building2, module: 'crm', accessLevel: 'pre-sales' },
      { label: 'Contacts', href: '/crm/contacts', icon: Contact, module: 'crm', accessLevel: 'pre-sales' },
      { label: 'Quotes', href: '/crm/quotes', icon: FileText, module: 'crm', accessLevel: 'pre-sales' },
      { label: 'Quote Builder', href: '/crm/quote-builder', icon: FilePlus, module: 'crm', accessLevel: 'pre-sales' },
      { label: 'Material Inquiries', href: '/crm/material-inquiries', icon: PackageSearch, module: 'crm', accessLevel: 'pre-sales' },
      { label: 'Demo Requests', href: '/crm/demo-requests', icon: Monitor, module: 'crm', accessLevel: 'pre-sales' },
      { label: 'Tasks', href: '/crm/tasks', icon: ListTodo, module: 'crm' },
      { label: 'Meetings', href: '/crm/meetings', icon: Video, module: 'crm' },
      { label: 'Calendar', href: '/crm/calendar', icon: Calendar, module: 'crm' },
      { label: 'Sales Orders', href: '/crm/sales-orders', icon: ShoppingCart, module: 'crm', accessLevel: 'post-sales' },
      { label: 'Purchase Requests', href: '/crm/purchase-requests', icon: FilePlus, module: 'crm', accessLevel: 'post-sales' },
    ],
  },
  {
    label: 'Warehouse',
    module: 'wms',
    icon: Warehouse,
    items: [
      { label: 'Dashboard', href: '/wms', icon: LayoutDashboard, module: 'wms' },
      { label: 'Inward / GRN', href: '/wms/inward', icon: PackageSearch, module: 'wms' },
      { label: 'Inspection', href: '/wms/inspection', icon: ClipboardCheck, module: 'wms' },
      { label: 'Repair', href: '/wms/repair', icon: Wrench, module: 'wms' },
      { label: 'Paint', href: '/wms/paint', icon: Paintbrush, module: 'wms' },
      { label: 'QC', href: '/wms/qc', icon: CheckCircle2, module: 'wms' },
      { label: 'Assign to Rack', href: '/wms/assign-rack', icon: LocateFixed, module: 'wms' },
      { label: 'Spares', href: '/wms/spares', icon: Cpu, module: 'wms' },
      { label: 'Outward', href: '/wms/outward', icon: Truck, module: 'wms' },
      { label: 'Dispatch Confirmations', href: '/wms/dispatches', icon: FileCheck, module: 'wms' },
      { label: 'Component History', href: '/wms/component-history', icon: History, module: 'wms' },
      { label: 'Checklists', href: '/wms/checklists', icon: ClipboardList, module: 'wms' },
      { label: 'Locations', href: '/wms/locations', icon: MapPin, module: 'wms' },
    ],
  },
  {
    label: 'Inventory',
    module: 'ims',
    icon: Boxes,
    items: [
      { label: 'Dashboard', href: '/ims', icon: LayoutDashboard, module: 'ims' },
      { label: 'Inventory', href: '/ims/inventory', icon: Boxes, module: 'ims' },
      { label: 'Parts / Products', href: '/ims/parts', icon: Package, module: 'ims' },
      { label: 'Categories', href: '/ims/categories', icon: FolderTree, module: 'ims' },
      { label: 'OEMs', href: '/ims/oems', icon: Factory, module: 'ims' },
      { label: 'Stock Items', href: '/ims/stock-items', icon: Tags, module: 'ims' },
      { label: 'PM Assignments', href: '/ims/pm-assignments', icon: UserCog, module: 'ims' },
      { label: 'Pricing', href: '/ims/pricing', icon: DollarSign, module: 'ims' },
      { label: 'Reports', href: '/ims/reports', icon: BarChart3, module: 'ims' },
    ],
  },
  {
    label: 'Procurement',
    module: 'procurement',
    icon: ClipboardList,
    items: [
      { label: 'Dashboard', href: '/procurement', icon: LayoutDashboard, module: 'procurement' },
      { label: 'Purchase Requests', href: '/procurement/pr', icon: FilePlus, module: 'procurement' },
      { label: 'Purchase Orders', href: '/procurement/po', icon: FileText, module: 'procurement' },
      { label: 'Vendors', href: '/procurement/vendors', icon: Store, module: 'procurement' },
      { label: 'GRN Matching', href: '/procurement/grn-matching', icon: ArrowLeftRight, module: 'procurement' },
      { label: 'PM Approvals', href: '/procurement/pm-approvals', icon: ShieldCheck, module: 'procurement' },
    ],
  },
  {
    label: 'Invoices',
    module: 'invoices',
    icon: Receipt,
    items: [
      { label: 'Dashboard', href: '/invoices', icon: LayoutDashboard, module: 'invoices' },
      { label: 'Sales Invoices', href: '/invoices/sales', icon: Receipt, module: 'invoices' },
      { label: 'Purchase Invoices', href: '/invoices/purchase', icon: FileText, module: 'invoices' },
      { label: 'Credit Notes', href: '/invoices/credit-notes', icon: FileBox, module: 'invoices' },
    ],
  },
  {
    label: 'Rentals',
    module: 'rentals',
    icon: CalendarClock,
    items: [
      { label: 'Dashboard', href: '/rentals', icon: LayoutDashboard, module: 'rentals' },
      { label: 'Contracts', href: '/rentals/contracts', icon: FileText, module: 'rentals' },
      { label: 'Orders', href: '/rentals/orders', icon: ShoppingCart, module: 'rentals' },
      { label: 'Asset Registry', href: '/rentals/assets', icon: Tags, module: 'rentals' },
      { label: 'Device Tracking', href: '/rentals/tracking', icon: MapPin, module: 'rentals' },
      { label: 'Billing', href: '/rentals/billing', icon: DollarSign, module: 'rentals' },
      { label: 'Returns', href: '/rentals/returns', icon: RotateCcw, module: 'rentals' },
      { label: 'Support Tickets', href: '/rentals/support', icon: ClipboardList, module: 'rentals' },
      { label: 'Partners', href: '/rentals/partners', icon: Building2, module: 'rentals' },
      { label: 'Analytics', href: '/rentals/analytics', icon: BarChart3, module: 'rentals' },
    ],
  },
  {
    label: 'Reports',
    module: 'reports',
    icon: BarChart3,
    items: [
      { label: 'Report Builder', href: '/reports', icon: BarChart3, module: 'reports' },
    ],
  },
  {
    label: 'Settings',
    module: 'settings',
    icon: Settings,
    items: [
      { label: 'Profile', href: '/settings/profile', icon: UserCircle, module: 'settings' },
      { label: 'User Management', href: '/settings/users', icon: Users, module: 'settings', requiredRole: 'ADMIN' },
      { label: 'Roles & Permissions', href: '/settings/roles', icon: Shield, module: 'settings', requiredRole: 'ADMIN' },
      { label: 'App Settings', href: '/settings/app', icon: Settings, module: 'settings' },
    ],
  },
]
